apiVersion: v1
kind: Secret
metadata:
  name: mern-app-secrets
  namespace: mern
  labels:
    app: mern-app
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://dushyanth520:904918@cluster0.kag8m76.mongodb.net/batman_auth?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "batman_dark_knight_secret_key_2024"
  GROQ_API_KEY: "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"
