apiVersion: v1
kind: Secret
metadata:
  name: mern-app-secrets
  namespace: mern
  labels:
    app: mern-app
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://USERNAME:PASSWORD@cluster.mongodb.net/DATABASE?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "your-secret-key-here-change-this-in-production"
  GROQ_API_KEY: "your-groq-api-key-here"